// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmG200EDe_uD0f7QyZQvmgFDsFaJUzl6k',
    appId: '1:678601586459:web:f4fb8871663732135085be',
    messagingSenderId: '678601586459',
    projectId: 'my-porki',
    authDomain: 'my-porki.firebaseapp.com',
    storageBucket: 'my-porki.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5DCF3fKMSUpeAE8uR_m_dkPxC2rH_LqM',
    appId: '1:678601586459:android:1ac2f846322f357d5085be',
    messagingSenderId: '678601586459',
    projectId: 'my-porki',
    storageBucket: 'my-porki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBfG3Dyq8kuz-nE7ZAd33qjW3NKHN-9RU',
    appId: '1:678601586459:ios:6e55a8f804378ee15085be',
    messagingSenderId: '678601586459',
    projectId: 'my-porki',
    storageBucket: 'my-porki.firebasestorage.app',
    iosBundleId: 'com.example.myPorki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBfG3Dyq8kuz-nE7ZAd33qjW3NKHN-9RU',
    appId: '1:678601586459:ios:6e55a8f804378ee15085be',
    messagingSenderId: '678601586459',
    projectId: 'my-porki',
    storageBucket: 'my-porki.firebasestorage.app',
    iosBundleId: 'com.example.myPorki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmG200EDe_uD0f7QyZQvmgFDsFaJUzl6k',
    appId: '1:678601586459:web:e28d87499064f56d5085be',
    messagingSenderId: '678601586459',
    projectId: 'my-porki',
    authDomain: 'my-porki.firebaseapp.com',
    storageBucket: 'my-porki.firebasestorage.app',
  );
}